# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = ydotoold
env = YDOTOOL_SOCKET,/run/user/1000/.ydotool_socket

exec-once = qs -c "QuickShell Bar"

exec-once = awww-daemon
exec-once = sleep 2 && awww img ~/.config/omarchy/current/background --transition-type=none

exec-once = [workspace special:whatsapp silent;move] chromium --profile-directory="Profile 1" --app=https://web.whatsapp.com

exec-once = [workspace special:ytmusic silent] chromium --profile-directory="Profile 1" --app="https://music.youtube.com" --hide-scrollbars

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = sudo /usr/local/bin/gesture-handler

exec-once = ~/.local/bin/walker-daemon

exec-once = clipse -listen

exec-once = ~/.local/bin/auto-split-ratio.sh

exec-once = firefoxpwa runtime -- --headless &

exec-once = ~/.local/bin/clipboard-watcher.sh

exec-once = hyprpm reload -n

#exec-once = uwsm-app -- qs -c noctalia-shell
