# Extra autostart processes
# exec-once = uwsm-app -- my-service
#
# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = ydotoold
env = YDOTOOL_SOCKET,/run/user/1000/.ydotool_socket

#exec-once = waybar -c ~/.config/waybar/config-main.jsonc
#exec-once = waybar -c ~/.config/waybar/config-secondary.jsonc

# Kill swaybg and start awww daemon on boot
exec-once = pkill swaybg; awww-daemon

# Set initial wallpaper after a brief delay
exec-once = sleep 2 && awww img ~/.config/omarchy/current/background --transition-type=grow --transition-duration=1.5 --transition-fps=60 --transition-pos=center
exec-once = ~/.config/waybar/scripts/nowplaying-listener.sh

exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#exec-once = /usr/lib/hyprwhspr/bin/hyprwhspr

exec-once = copyq --start-server
exec-once = clipse --listen
exec-once = ~/.config/waybar/scripts/nowplaying-watch.sh
exec-once = ~/.local/bin/clipboard-watcher.sh

exec-once = uwsm-app -- swayosd-server
exec-once = qs -c bar

#exec-once = waybar -c ~/.config/waybar/config-main.jsonc & sleep 0.5 && waybar -c ~/.config/waybar/config-secondary.jsonc
