# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = ydotoold
env = YDOTOOL_SOCKET,/run/user/1000/.ydotool_socket

#exec-once = pkill swaybg; awww-daemon
#exec-once = sleep 2 && awww img ~/.config/omarchy/current/background --transition-type=grow --transition-duration=1.5 --transition-fps=60 --transition-pos=center

exec-once = [workspace special:whatsapp silent] chromium --profile-directory="Profile 1" --app=https://web.whatsapp.com

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = sudo /usr/local/bin/gesture-handler

exec-once = ~/.local/bin/walker-daemon

exec-once = clipse -listen

exec-once = ~/.local/bin/auto-split-ratio.sh

exec-once = firefoxpwa runtime -- --headless &
