# Just a dash of opacity by default
windowrule = opacity 1 0.9, match:class .*

# YT Music special workspace
windowrule = match:title ^(YouTube Music)$, workspace special:ytmusic, float on, size 1139 746, center on
windowrule = match:class ^(chrome-music\.youtube\.com__-Profile_1)$, workspace special:ytmusic, float on, size 1139 746, center on

# FotMob special workspace
windowrule = match:title ^(FotMob - Football Live Scores)$, workspace special:fotmob, float on, size 389 730, move 1028 55
windowrule = match:class ^(chrome-.*fotmob.*)$, workspace special:fotmob
windowrule = match:class ^(chrome-www\.fotmob\.com.*\.*)$, float on, size 389 730, move 1028 55

# Alacritty
windowrule = match:class ^floating-terminal$, float on
windowrule = match:class ^floating-terminal$, center on
windowrule = match:class ^floating-terminal$, size 500 600


# Reddit special workspace
windowrule = match:class ^(chrome-www\.reddit\.com__-Profile_1)$, workspace special:reddit, float on, size 592 730, center on, opacity 1.0 0.9

# Authenticator
windowrule = match:class ^(com\.belmoussaoui\.Authenticator)$, float on, size 460 294, center on

windowrule = match:class ^(clipse)$, float on, size 622 652, center on

# LocalSend
windowrule = match:class ^(localsend)$, float on, size 500 650, center on

# Timeshift window rule - floating and centered
windowrule = match:class ^(timeshift-gtk)$, float on, center on, size 900 650

# WhatsApp special workspace
windowrule = match:class ^(chrome-web\.whatsapp\.com__-Profile_1)$, workspace special:whatsapp, float on, size 1139 746, center on, opacity 1.0 0.9

# To Do special workspace
windowrule = match:class ^(chrome-to-do\.office\.com__tasks_inbox-Profile_1)$, workspace special:todo silent, float on, size 376 715, move 1042 61
windowrule = match:class ^(chrome-to-do\.office\.com__tasks_inbox-Default)$, workspace special:todo silent, float on, size 376 715, move 1042 61

# Alacritty snippet-picker
windowrule = match:class ^(Alacritty)$, match:title ^(snippet-picker)$, float on, size 600 400, center on

# Remmina special workspace
windowrule = match:class ^(org\.remmina\.Remmina)$, workspace special:remmina silent

# Snippet picker window rule
windowrule = match:title ^(rofi - Snippet:)$, float on, size 300 300, center on

# GNOME Cheese
windowrule = match:class ^(org\.gnome\.Cheese)$, float on, size 608 538, center on

# X (Twitter) special workspace
windowrule = match:class ^(chrome-x\.com__-Profile_1)$, workspace special:x, float on, size 592 730, move 26 53, opacity 1.0 0.9

# jome emoji picker
windowrule = match:class ^jome$, float on, size 652 510, center on

# Snippet picker (Alacritty)
windowrule = match:class ^Alacritty$, match:title ^snippet-picker$, float on, size 355 194, center on

#Handy
windowrule = match:class ^(handy)$, float on, center on, size 1021 727

# Text format picker (foot)
windowrule = match:class ^format-picker$, float on, size 500 400, center on
